/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat;
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CampaignId = IDL.Nat;
export const Campaign = IDL.Record({
  'id' : CampaignId,
  'status' : IDL.Text,
  'clicks' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'impressions' : IDL.Nat,
  'targetUrl' : IDL.Text,
  'spent' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'budget' : IDL.Nat,
});
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'isSponsored' : IDL.Bool,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'likes' : IDL.Vec(IDL.Principal),
  'imageUrl' : IDL.Text,
  'sponsoredLabel' : IDL.Text,
  'commentCount' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const VideoId = IDL.Nat;
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'isSponsored' : IDL.Bool,
  'views' : IDL.Nat,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'likes' : IDL.Vec(IDL.Principal),
  'videoUrl' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'isAdmin' : IDL.Bool,
  'avatar' : ExternalBlob,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const RevenueStats = IDL.Record({
  'CTR' : IDL.Float64,
  'totalImpressions' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalClicks' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCampaign' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Campaign],
      [],
    ),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Post], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [Product],
      [],
    ),
  'createVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Video],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [Order], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getProductById' : IDL.Func([ProductId], [Product], ['query']),
  'getProducts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getRevenueStats' : IDL.Func([], [RevenueStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideos' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Video)], ['query']),
  'incrementViewCount' : IDL.Func([VideoId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'likeVideo' : IDL.Func([VideoId], [], []),
  'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'makeAdmin' : IDL.Func([IDL.Principal], [], []),
  'placeOrder' : IDL.Func([], [Order], []),
  'recordClick' : IDL.Func([CampaignId], [], []),
  'recordImpression' : IDL.Func([CampaignId], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [UserProfile],
      [],
    ),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCampaignStatus' : IDL.Func([CampaignId, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat;
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CampaignId = IDL.Nat;
  const Campaign = IDL.Record({
    'id' : CampaignId,
    'status' : IDL.Text,
    'clicks' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'impressions' : IDL.Nat,
    'targetUrl' : IDL.Text,
    'spent' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'budget' : IDL.Nat,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'isSponsored' : IDL.Bool,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'likes' : IDL.Vec(IDL.Principal),
    'imageUrl' : IDL.Text,
    'sponsoredLabel' : IDL.Text,
    'commentCount' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const VideoId = IDL.Nat;
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'isSponsored' : IDL.Bool,
    'views' : IDL.Nat,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'likes' : IDL.Vec(IDL.Principal),
    'videoUrl' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'isAdmin' : IDL.Bool,
    'avatar' : ExternalBlob,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const RevenueStats = IDL.Record({
    'CTR' : IDL.Float64,
    'totalImpressions' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalClicks' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCampaign' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Campaign],
        [],
      ),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [Post], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [Product],
        [],
      ),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Video],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [Order], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getProductById' : IDL.Func([ProductId], [Product], ['query']),
    'getProducts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getRevenueStats' : IDL.Func([], [RevenueStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideos' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Video)], ['query']),
    'incrementViewCount' : IDL.Func([VideoId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'likeVideo' : IDL.Func([VideoId], [], []),
    'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'makeAdmin' : IDL.Func([IDL.Principal], [], []),
    'placeOrder' : IDL.Func([], [Order], []),
    'recordClick' : IDL.Func([CampaignId], [], []),
    'recordImpression' : IDL.Func([CampaignId], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [UserProfile],
        [],
      ),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCampaignStatus' : IDL.Func([CampaignId, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };