/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Campaign {
  'id' : CampaignId,
  'status' : string,
  'clicks' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'impressions' : bigint,
  'targetUrl' : string,
  'spent' : bigint,
  'imageUrl' : string,
  'budget' : bigint,
}
export type CampaignId = bigint;
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Post {
  'id' : PostId,
  'content' : string,
  'isSponsored' : boolean,
  'authorId' : Principal,
  'createdAt' : bigint,
  'likes' : Array<Principal>,
  'imageUrl' : string,
  'sponsoredLabel' : string,
  'commentCount' : bigint,
}
export type PostId = bigint;
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export type ProductId = bigint;
export interface RevenueStats {
  'CTR' : number,
  'totalImpressions' : bigint,
  'totalRevenue' : bigint,
  'totalClicks' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'isAdmin' : boolean,
  'avatar' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'thumbnailUrl' : string,
  'isSponsored' : boolean,
  'views' : bigint,
  'authorId' : Principal,
  'createdAt' : bigint,
  'likes' : Array<Principal>,
  'videoUrl' : string,
}
export type VideoId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[PostId, string], undefined>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCampaign' : ActorMethod<[string, bigint, string, string], Campaign>,
  'createPost' : ActorMethod<[string, string, boolean], Post>,
  'createProduct' : ActorMethod<
    [string, string, bigint, string, string, bigint],
    Product
  >,
  'createVideo' : ActorMethod<[string, string, string, boolean], Video>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCurrentUser' : ActorMethod<[], [] | [UserProfile]>,
  'getOrderById' : ActorMethod<[OrderId], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getProductById' : ActorMethod<[ProductId], Product>,
  'getProducts' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getRevenueStats' : ActorMethod<[], RevenueStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideos' : ActorMethod<[bigint, bigint], Array<Video>>,
  'incrementViewCount' : ActorMethod<[VideoId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'likeVideo' : ActorMethod<[VideoId], undefined>,
  'listCampaigns' : ActorMethod<[], Array<Campaign>>,
  'makeAdmin' : ActorMethod<[Principal], undefined>,
  'placeOrder' : ActorMethod<[], Order>,
  'recordClick' : ActorMethod<[CampaignId], undefined>,
  'recordImpression' : ActorMethod<[CampaignId], undefined>,
  'registerUser' : ActorMethod<
    [string, string, ExternalBlob, string],
    UserProfile
  >,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCampaignStatus' : ActorMethod<[CampaignId, string], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];